### ISSUE TITLE
illegal instruction running RISCV-ELF on the FPAG

### ISSUE THREAD

**Issue by JunnanLi** [pulp-platform/ariane#284]
Hi,
@zarubaf 

I meet a "illegal instruction" when running qsort.riscv (generated by riscv-tools/riscv-test) on the FPGA. Do you know how to run benchmarks of ristv-test on FPGA?

**Comment by zarubaf** [comment]
The problem is that you don’t have permissions to read performance counters in userspace (and accesses to privileged CSRs trap as illegal instructions). Ariane doesn’t implement `[m|s]counteren` (yet), which is a perfectly legal. There is a pull request which should implement the CSR which for some reason breaks the Linux boot.
