### ISSUE TITLE
boot from flash

### ISSUE THREAD

**Issue by mathmax12** [pulp-platform/ariane#299]
Hi,
 I want to know is it possible to put the FPGA bitstream, zero boot loader, first boot loader, Linux image together to the flash?
is there such flow I can follow?

Thanks.

**Comment by Moschn** [comment]
The bitstream includes the zero-stage boot loader in a ROM and as far as I know we had that working at some point. There should be tutorials by Xilinx to put a bitstream into flash.

We have not tried to put the first-stage bootloader (bbl) and the linux image in flash. It should certainly be possible if there is enough space. However, it would need some changes in the zero-stage bootloader such as adding a bare-metal driver for the SPI flash.

**Comment by mathmax12** [comment]
Thanks.

**Comment by mathmax12** [comment]
@Moschn,

Can you show more details about this?
Thanks

**Comment by Moschn** [comment]
There is a digilent tutorial for example: https://reference.digilentinc.com/learn/programmable-logic/tutorials/genesys-2-programming-guide/start

**Comment by mathmax12** [comment]
Hi @Moschn ,
Thanks for.
I know the flow of programming the Genesys2 board through Quad SPI Flash.
My question is how to put the **bitstream, bootloader, and Linux image** together to generate a single file (e.g., .bin or .mcs) file, after which I can put this single file to the Quad SPI Flash for booting the Linux system.

I know the VIvado SDK can do that targeting the Zynq SOC (ARM hardcore).
Is there a way that we can do the same thing for Ariane core?

**Comment by Moschn** [comment]
At the moment this is not possible. The zero stage bootloader explicitly looks for an SD card connected over SPI and loads the bbl+linux from there. 

In order to support loading bbl+linux from SPI flash one needs to add the following:
- write a driver in the zero stage bootloader for the SPI flash
- extract the bbl+linux image somehow from the flash
  - probably requires filesystem support

**Comment by mathmax12** [comment]
Is there any documentation to follow?
Does the Ariane have any plan to do this?

**Comment by Moschn** [comment]
We do not plan to add this in the near future AFAIK. 

If you want to get your hands dirty: [fpga/src/bootrom](fpga/src/bootrom).

The SPI driver should be really easy since SPI flash is directly addressable. You would need to connect it to the system bus first though. After that you need to read up on how xilinx manages their bitstream in the SPI flash and then find a way to put the boot image next to the bitstream (thats where i think we would need a file system).
