### ISSUE TITLE
run dhrystone with questasim

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/ariane#41]
Hi, I am getting the following issue while running dhrystone in questasim 10.6 : 
![image](https://user-images.githubusercontent.com/36438648/39304581-6747fba4-495a-11e8-97ed-5e85522540fb.png)

![image](https://user-images.githubusercontent.com/36438648/39305196-858784b6-495c-11e8-824d-87eb17881b93.png)

I have generate an elf and an hex.

Can someone help me ?

**Comment by raulbehl** [comment]
I guess with the current setup it is not possible to run dhrystone with Questasim as the project currently doesn't support the "printf" function. Basically, the host communication isn't setup yet for Questasim. You should use Verilator in order to run those benchmarks or possible try removing printfs from dhrystone and compiling it using [this](https://github.com/pulp-platform/ariane#running-custom-c-code).

**Comment by lfernand4** [comment]
I use verilator : 
![image](https://user-images.githubusercontent.com/36438648/39311887-6de506be-496e-11e8-80cf-df93933cd6ec.png)
But I have Dhrystones per Second:  1281.0  (0.76D/Mhz)
